# ============== built-in ==============
spring:
  main:
    banner-mode: off
  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB
  mvc:
    async:
      # resolution for AsyncRequestTimeoutException when download too slow
      request-timeout: -1
  web:
    resources:
      static-locations:
        - "classpath:/META-INF/resources/"
        - "classpath:/resources/"
        - "classpath:/static/"
        - "classpath:/public/"

server:
  port: 8080
  tomcat:
    max-swallow-size: 500MB

mybatis-plus:
  global-config:
    banner: false
  configuration:
    log-impl: org.apache.ibatis.logging.nologging.NoLoggingImpl

logging:
  config: classpath:logback-spring.xml
  level:
    _org.springframework.web.servlet.HandlerMapping.Mappings: off
    com.alibaba.druid.pool.PreparedStatementPool: info
    com.ccm.web: debug
    com.zaxxer.hikari: info
    io.netty: info
    io.netty.handler.logging.LoggingHandler: debug
    net.sf.ehcache: info
    org.apache: info
    org.apache.catalina.core.ContainerBase: warn
    org.apache.catalina.core.StandardContext: warn
    org.apache.catalina.core.StandardService: warn
    org.apache.catalina.core.StandardEngine: warn
    org.apache.coyote.http11.Http11NioProtocol: warn
    org.hibernate: info
    org.hibernate.validator.internal.util.Version: warn
    org.jboss.logging: warn
    org.mybatis.spring.mapper.ClassPathMapperScanner: info
    org.reflections.Reflections: warn
    org.springframework.orm.jpa.JpaTransactionManager: info
    org.springframework: info
    org.springframework.boot.autoconfigure.web.servlet.WelcomePageHandlerMapping: warn
    org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext: warn
    org.springframework.context.support.PostProcessorRegistrationDelegate: warn
    org.springframework.context.annotation.AutoProxyRegistrar: off
    org.springframework.data.repository.config.RepositoryConfigurationDelegate: warn
    org.springframework.web.servlet.DispatcherServlet: warn
    oshi.software.os.linux: error
    oshi.util.FileUtil: error
    sun.rmi: info

# ============== custom ==============
db:
  enabled: false
  user: root
  password: root
  name: test
  host: localhost
  port: 33061

#serve_static: "/your/path/to/static/"
